export const DICT = {
  es: {
    nav_help: "Ayuda",
    kicker: "Invitación exclusiva",
    invite_kicker: "Estás cordialmente invitado a",
    event_title: "Vivir la nueva experiencia de",
    event_brand: "CM Airlines",
    slogan: "Vive la nueva experiencia de CM Airlines",
    d_date_l: "Fecha", d_date_v: "08 JUL 2026",
    d_time_l: "Hora", d_time_v: "7:00 PM",
    d_place_l: "Lugar", d_place_v: "Aeropuerto Toncontín, Hangar DIVESA",
    d_dress_l: "Vestimenta", d_dress_v: "Cóctel",
    step1: "Check-In", step2: "Boarding Pass", step3: "Abordaje",
    checkin_title: "Web Check-In",
    checkin_sub:
      "Ingresa tu número de identidad para confirmar tu asistencia y emitir tu boarding pass digital.",
    id_label: "Número de identidad", id_ph: "0801-1990-00000",
    cta: "Confirmar asistencia", cta_loading: "Emitiendo boarding pass…",
    secure_note: "Tus datos están seguros · Solo para validar tu invitación",
    err_required: "Por favor ingresa tu número de identidad.",
    err_not_found:
      "Lo sentimos, no podemos confirmar tu asistencia. Verifica tu número de identidad o contacta a tu representante.",
    boarding_kicker: "Check-in completado",
    boarding_title: "Tu boarding pass está listo",
    boarding_sub: "Preséntalo para tu ingreso al evento.",
    bp_title: "BOARDING PASS", bp_subtitle: "PASE DE ABORDAR",
    bp_from_city: "Tegucigalpa", bp_to_city: "Nueva Experiencia\nCM Airlines",
    bp_passenger: "Pasajero", bp_flight: "Vuelo", bp_date: "Fecha", bp_boarding: "Abordaje",
    bp_gate: "Puerta", bp_seat: "Asiento", bp_class: "Clase", bp_class_v: "Cóctel",
    bp_terminal: "Terminal", bp_time: "Evento", bp_seq: "Sec.",
    stub_scan: "Escanea al ingresar al evento",
    btn_download: "Descargar pase", btn_cal: "Agregar al calendario", btn_back: "Volver al check-in",
    rsvp_title: "Confirma tu asistencia", rsvp_sub: "RSVP con tu representante",
    footer: "CM Airlines · Vive la nueva experiencia",
    pax_guest: "INVITADO",
    ics_summary: "Evento CM Airlines 2026",
  },
  en: {
    nav_help: "Help",
    kicker: "Exclusive invitation",
    invite_kicker: "You are cordially invited to",
    event_title: "Experience the new",
    event_brand: "CM Airlines",
    slogan: "Experience the new CM Airlines",
    d_date_l: "Date", d_date_v: "JUL 08 2026",
    d_time_l: "Time", d_time_v: "7:00 PM",
    d_place_l: "Venue", d_place_v: "Toncontín Airport, DIVESA Hangar",
    d_dress_l: "Dress code", d_dress_v: "Cocktail",
    step1: "Check-In", step2: "Boarding Pass", step3: "Boarding",
    checkin_title: "Web Check-In",
    checkin_sub:
      "Enter your ID number to confirm your attendance and issue your digital boarding pass.",
    id_label: "ID number", id_ph: "0801-1990-00000",
    cta: "Confirm attendance", cta_loading: "Issuing boarding pass…",
    secure_note: "Your data is safe · Only used to validate your invitation",
    err_required: "Please enter your ID number.",
    err_not_found:
      "Sorry, we cannot confirm your attendance. Please check your ID number or contact your representative.",
    boarding_kicker: "Check-in complete",
    boarding_title: "Your boarding pass is ready",
    boarding_sub: "Present it at the event entrance.",
    bp_title: "BOARDING PASS", bp_subtitle: "DIGITAL PASS",
    bp_from_city: "Tegucigalpa", bp_to_city: "New CM\nExperience",
    bp_passenger: "Passenger", bp_flight: "Flight", bp_date: "Date", bp_boarding: "Boarding",
    bp_gate: "Gate", bp_seat: "Seat", bp_class: "Class", bp_class_v: "Cocktail",
    bp_terminal: "Terminal", bp_time: "Event", bp_seq: "Seq.",
    stub_scan: "Scan at event entrance",
    btn_download: "Download pass", btn_cal: "Add to calendar", btn_back: "Back to check-in",
    rsvp_title: "Confirm your attendance", rsvp_sub: "RSVP with your representative",
    footer: "CM Airlines · Experience the new",
    pax_guest: "GUEST",
    ics_summary: "CM Airlines Event 2026",
  },
};
